### ISSUE TITLE
Fix link to online view of specification 

### ISSUE THREAD

**Issue by tuckerzp** [EasyDynamics/oscal-rest#27]
The `README` page links to: https://editor.swagger.io/?url=https://raw.githubusercontent.com/EasyDynamics/oscal-rest/develop/openapi.yaml 

Which has an error of:
![image](https://user-images.githubusercontent.com/39490074/124772991-87721600-df0a-11eb-84dd-7abebd01cc39.png)

The raw `.yaml` file it is supposed to link to has a `token` not given as seen: https://raw.githubusercontent.com/EasyDynamics/oscal-rest/develop/openapi.yaml?token=AJNJEGW46DSI6AJJZ45W5TDA4W2GQ

**Comment by kylelaker** [comment]
@tuckerzp can you confirm that this is now resolved?

**Comment by tuckerzp** [comment]
@rgauss you were right! I will close issue now
