### ISSUE TITLE
Clarify the behavior of `PATCH` operations (related to PUT/POST)

### ISSUE THREAD

**Issue by laurelmay** [EasyDynamics/oscal-rest#52]
A `PATCH` should be used for partial updates to an existing object and when a `PATCH` body includes an update to a type defined as a list should be purely additive (the items from the body should be added to the list and should not replace the full list).

For example, consider the `revisions` field within the metadata. The API specification does not supply a specific route for adding revisions; however, users may want to add a revision without sending data for previous revisions. The following operation should simply _add_ a new revision and make no other modifications to the object

```
PATCH /system-security-plans/:id

{
  "metadata": {
    "revisions": [
      { "version": "20220517" }
    ]
  }
}
```

(note the UUID is omitted with the assumption that #51 is accepted as-is and that similar guidance around not requiring UUIDs in bodies will apply to a `PATCH`)

For comparison, a `PUT` operations should always result in a full update to (or essentially, replacement of) an object; a `POST` should always be used to create new objects.

**Comment by kperk103** [comment]
@kylelaker Where would you recommend I add this clarification? I was considering putting it in the section "Partial Payloads in PATCH Requests" but am not sure if it would be better to create another section instead

**Comment by laurelmay** [comment]
Great question @kperk103! Think right in this section of `openapi.yaml` would be perfect!

https://github.com/EasyDynamics/oscal-rest/blob/4365daa67fc6ba67f2fa95428b1ed338ad0a86ef/openapi.yaml#L42

**Comment by kperk103** [comment]
@kylelaker thanks! Also, can I use the example you gave in your description of the task?

**Comment by laurelmay** [comment]
Absolutely! We just want to make sure to provide a little context in addition to the example. And feel free to use a _better_ example if you're aware of one.

**Comment by laurelmay** [comment]
Thank you for the work on this @kperk103!
