### ISSUE TITLE
JSON Only for Non-OSCAL Files

### ISSUE THREAD

**Issue by brian-ruf-ezd** [EasyDynamics/oscal-rest#74]
We have made the decision to have the API work exclusively in JSON for all interactions that do not involve the transfer of a full OSCAL file. The specification needs to be updated to remove the XML choice and return content from all other endpoints.

Only in the following cases  will JSON, XML and YAML formats be supported by the specification:
- `GET /[model-name]/{Identifier}`
- `GET /[model-name]/{Identifier}/snapshot/{Identifier}`
- `GET /profile/{Identifier}/resolved-catalog`
- `GET /profile/{Identifier}/resolved-snapshot/{Identifier}`
- `POST /[model-name]` - accepts XML, JSON, or YAML
- `PUT /[model-name]/{Identifier}` - accepts XML, JSON, or YAML

For the `GET` endpoints combinations, the HTTP header `Content-type` may be set to one of the following:
-  No `Content-type` specified, return the OSCAL file in JSON format;
- `application/json` return the OSCAL file in JSON format;
- `application/xml` (preferred by RFC 7303) or `text/xml` (deprecated by RFC 7303) or `application/oscal+xml` return the OSCAL file in XML format; or
- `application/yaml` (preferred) or `text/yaml` return the OSCAL file in YAML format.
- If the `Content-type` is present, but set to something other than the above, return error 422 Unprocessable Content with a message that says, "[Content-type-value] Content-type header is invalid for OSCAL content."

The two `POST` and `PUT` endpoints accept XML, JSON or YAML and the implementation converts to the other two formats. Any return code (201 Successful Operation, 4xx Error) is always in JSON.

All methods associated with attachments endpoints (`/[model]/{Identifier}/attachment` and `/[model]/{Identifier}/attachment/{Identifier}` remain able to handle any file type. (no change)

All other `GET`, `PUT`, and `POST` endpoints strictly exchange JSON unless otherwise noted.

**Comment by brian-ruf-ezd** [comment]
2024-01-25 complete and reviewed.

**Comment by zhaque44** [comment]
how can  get unsubcribed from these messages? i keep getting pinged it needs to stop @brian-comply0
