### ISSUE TITLE
GET Resolved Profile Returns Content Incorrect

### ISSUE THREAD

**Issue by brian-ruf-ezd** [EasyDynamics/oscal-rest#76]
The specification for `GET /profile/{identifier}/resolved-catalog` method/endpoint should return a valid OSCAL catalog in XML, JSON and YAML formats. 

Revised: 2024-03-25

**Comment by zhaque44** [comment]
Another useful notification for me @brian-comply0 can we have someone from IT remove me from these emails and notifications? I unsubscribed already

**Comment by brian-comply0** [comment]
@zhaque44 - can you contact us directly with these instead of posting comments to the issues?
This is the first I heard this is an issue for you.

**Comment by brian-ruf-ezd** [comment]
2024-02-07 deferring until controls internal MVP is achieved. Moving to next sprint just to track.

**Comment by brian-comply0** [comment]
The "string" issue was related to this display of the spec, not a problem with the spec; however, it was noted that this is returning catalog-snapshot. It should be returning an actual OSCAL catalog in XML, JSON or YAML formats.

**Comment by brian-ruf-ezd** [comment]
The fix for `GET /profile/{id}/resolved-catalog` looks great!
@brian-comply0 missed that this should also be fixed for `GET /profile/{id}/resolved-snapshot/{id}`

**Comment by brian-ruf-ezd** [comment]
This is now addressed for both `GET /profile/{id}/resolved-catalog` and `GET /profile/{id}/resolved-snapshot/{id}` in PR #72. 
The XML returns for each of these suffers the same problem described in issue #78 and should be addressed as part of that issue. Closing this one.
