### ISSUE TITLE
Get Snapshots Should Return Valid OSCAL Content

### ISSUE THREAD

**Issue by brian-ruf-ezd** [EasyDynamics/oscal-rest#77]
For the following `GET` endpoints, the return content incorrectly adds `-snapshot` to the root element for all three return formats (XML, JSON, and YAML):
- `GET /{model-name}/{identifier}`
- `GET /{model-name}/{identifier}/snapshot/{identifier}`
- `GET /profile/{identifier}/resolved-snapshot/{identifier}`

These endpoints should always return a valid OSCAL file. Adding `-snapshot` to the root element invalidates the OSCAL content by creating root elements not recognized by OSCAL content validation capabilities.

**Comment by brian-ruf-ezd** [comment]
2024-02-07 deferring until controls internal MVP is achieved. Moving to next sprint just to track.

**Comment by brian-ruf-ezd** [comment]
Made good progress on the collection of issues. This one will be addressed in sprint 68.

**Comment by pjavan** [comment]
@mpemy and @brian-comply0 what do we need to do to get this finished?

**Comment by brian-ruf-ezd** [comment]
With the exception of the XML problem noted in issue #78, this is satisfied. Closing.
