### ISSUE TITLE
Version Handling

### ISSUE THREAD

**Issue by brian-ruf-ezd** [EasyDynamics/oscal-rest#79]
As an author of software that calls the OSCAL REST OpenAPI specification, I want to be able to indicate which version of the API spec I am using. This will be important once we get beyond version 1.0.0. 

The syntax for identifying the version should be selected, such that it is optional. The implementation may elect to either always require the version or allow it to be omitted. Any implementation that allows the version to be omitted must use the latest available version when no version is specified. 

The REST API specification must also provide a mechanism for indicating what version(s) of the specification are supported by a specific implementation.

**Comment by cdroblee** [comment]
@brian-comply0 definitely good to be thinking about this now.

There are lots of established best practices on how to implement API versioning. I generally prefer URI-based versioning (e.g. `https://api.oscal.io/api/v1/catalog`) as it's the most explicit and easiest to control, but header and body versioning are also quite common:

<img width="685" alt="image" src="https://github.com/EasyDynamics/oscal-rest/assets/147451915/a52b2537-0284-4b19-b8b5-520664a6b198">


Here's a good [summary](https://kodekloud.com/blog/api-versioning-best-practices/) of different best practices.

**Comment by cdroblee** [comment]
@brian-comply0 definitely good to be thinking about this now.

There are lots of established best practices on how to implement API versioning. I generally prefer URI-based versioning (e.g. `https://api.oscal.io/api/v1/catalog`) as it's the most explicit and easiest to control, but header and body versioning are also quite common:

<img width="685" alt="image" src="https://github.com/EasyDynamics/oscal-rest/assets/147451915/a52b2537-0284-4b19-b8b5-520664a6b198">


Here's a good [summary](https://kodekloud.com/blog/api-versioning-best-practices/) of different best practices.

**Comment by brian-ruf-ezd** [comment]
_Body Versioning_ sounds like it introduces additional complexity for `PUT` and `POST` methods used for transmitting complete OSCAL documents. The OSCAL content could be in XML, JSON or YAML. The endpoints would need to require the content be wrapped as multi-part mime in order to include the syntax version as JSON. 

I believe we should set this one aside and consider only _URI Versioning_ and _Header Versioning_.

**Comment by brian-ruf-ezd** [comment]
We will use [Semantic Versioning](https://semver.org/) for the version number, and URI versioning to specify the version of the API being used.

**Comment by brian-ruf-ezd** [comment]
@mpemy's OpenAPI generation capability can now insert whatever version number the product owner specifies for a given release, and the [supporting documentation](https://docs.oscal.io/docs/supporting-information) cites the use of Semantic Versioning. Closing issue.
